# Generated by Django 6.0.2 on 2026-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commit',
            field=models.CharField(default='nothing', max_length=50),
        ),
    ]
