# Generated by Django 6.0.2 on 2026-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_hackathonidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=50)),
            ],
        ),
    ]
